Fix `TestBlocksCleaner_RaceCondition...` flakiness (#16217)
**What this PR does**

Fixes the flakiness of
`TestBlocksCleaner_RaceCondition_CleanerUpdatesBucketIndexWhileAnotherCleanerDeletesBlocks`,
which sometimes fails with `upload already in progress for
user-1/bucket-index.json.gz, retry, creating swap file failed: ...`

```
--- FAIL: TestBlocksCleaner_RaceCondition_CleanerUpdatesBucketIndexWhileAnotherCleanerDeletesBlocks (0.17s)
    --- FAIL: TestBlocksCleaner_RaceCondition_CleanerUpdatesBucketIndexWhileAnotherCleanerDeletesBlocks/the_2nd_cleaner_fetches_new_deletion_marks_after_the_1st_cleaner_has_started_deleting_blocks_for_the_new_deletion_marks (0.10s)
        blocks_cleaner_test.go:1730:
            	Error Trace:	/__w/mimir/mimir/pkg/compactor/blocks_cleaner_test.go:1730
            	            				/usr/local/go/src/runtime/asm_amd64.s:1771
            	Error:      	Received unexpected error:
            	            	upload already in progress for user-1/bucket-index.json.gz, retry, creating swap file failed: open /tmp/TestBlocksCleaner_RaceCondition_CleanerUpdatesBucketIndexWhileAn1005483577/001/user-1/bucket-index.json.gz.swap: file exists
            	            	upload bucket index
            	            	github.com/grafana/mimir/pkg/storage/tsdb/bucketindex.WriteIndex
            	            		/__w/mimir/mimir/pkg/storage/tsdb/bucketindex/storage.go:99
            	            	github.com/grafana/mimir/pkg/compactor.(*BlocksCleaner).cleanUser
            	            		/__w/mimir/mimir/pkg/compactor/blocks_cleaner.go:517
            	            	github.com/grafana/mimir/pkg/compactor.TestBlocksCleaner_RaceCondition_CleanerUpdatesBucketIndexWhileAnotherCleanerDeletesBlocks.func3.2
            	            		/__w/mimir/mimir/pkg/compactor/blocks_cleaner_test.go:1730
            	            	runtime.goexit
            	            		/usr/local/go/src/runtime/asm_amd64.s:1771
            	Test:       	TestBlocksCleaner_RaceCondition_CleanerUpdatesBucketIndexWhileAnotherCleanerDeletesBlocks/
```

**Why it fails randomly**

The thanos-io/objstore update in
https://github.com/grafana/mimir/pull/15939 brought
https://github.com/thanos-io/objstore/pull/178, which adds support for
conditional writes. The filesystem bucket implementation for it achieves
this with temporary file locks (the `<name>.swap` file) that are held
during an Upload, and can fail to be acquired. The catch is this mutual
exclusion was introduced for all uploads, no matter if conditional or
not. This makes it so concurrent Upload calls now fail.

The test in question is exercising two cleaners concurrently working on
the same tenant, and they sometimes happen to call Upload on the same
object at the same time.

**The fix**

I'd expect the filesystem bucket to mimic S3 and friends by allowing
concurrent writes with [last-writer-wins
semantics](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html#Concurrent-applications).
I looked into fixing this myself upstream, but it was not trivial, and
every solution I thought of had its caveats.

So I opted to just fix our test by ensuring `Upload` calls are
serialized.