[mimir-distributed-release-6.1] Revert "Compartments: validate per-compartment id flags in jsonnet" (#15851)
Backport 66618c9b0ca46c9882d7eeb2006315ce7b130d1e from #15840 <sup>[job
run](https://github.com/grafana/mimir/actions/runs/28233674968)</sup>

---

Reverts grafana/mimir#15824

CI on `main` has been failing with errors like the following since this
was merged, so reverting to unblock
([logs](https://github.com/grafana/mimir/actions/runs/28183731786/job/83479993819)):

```
Error: evaluating jsonnet: RUNTIME ERROR: case 8: expected compartment-id extraction error, got: The Deployment or StatefulSet "distributor" sets "-ingest-storage.kafka.address=kafka-wc-0.default.svc.cluster.local.:9092", but a global deployment reads from every write compartment's Kafka cluster, so the address must contain the "<write-compartment-id>" placeholder.
	/__w/mimir/mimir/jsonnet-tests/environments/test/main.jsonnet:(115:1)-(118:3)	
	During evaluation	
```

Co-authored-by: mimir-github-bot[bot] <199097951+mimir-github-bot[bot]@users.noreply.github.com>
Co-authored-by: Charles Korn <charleskorn@users.noreply.github.com>